#image: java:8
#image: selenium/standalone-firefox:2.53.0
#image: pdouble16/openshift-s2i-grails2
image: pdouble16/bitbucket-pipeline-browsers

pipelines:
  default:
    - step:
        script:
          - "JAVA_HOME=/usr/lib/jvm/java-8-oracle ./grailsw test-app"
