image: pdouble16/bitbucket-pipeline-browsers:1.1_46.0.1_51_2.1.1

pipelines:
  default:
    - step:
        script:
          - ./grailsw -Dgeb.env=phantomjs test-app
          - ./grailsw -Dgeb.env=firefox test-app
          - ./grailsw -Dgeb.env=chrome test-app
