version: '2'

services:
  jenkins:
    image: jenkinsci/workflow-demo
    ports:
      - "2222:2222"
      - "8080:8080"
      - "8081:8081"
      - "9418:9418"
    links:
      - selenium-hub:hub

  selenium-hub:
    image: selenium/hub:2.53.0
    ports:
      - "4444"

  node-chrome:
    image: selenium/node-chrome:2.53.0
    links:
      - selenium-hub:hub
    environment:
      - HUB_PORT=tcp://hub:4444
      - HUB_PORT_4444_TCP=tcp://hub:4444
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444

  node-firefox:
    image: selenium/node-firefox:2.53.0
    links:
      - selenium-hub:hub
    environment:
      - HUB_PORT=tcp://hub:4444
      - HUB_PORT_4444_TCP=tcp://hub:4444
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444

